<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>26.1.8</Version>
    <Authors>Daniel T. Houck</Authors>
    <Company>batpox/metalBlender</Company>
    <TargetFrameworks>net48;net8.0;net10.0</TargetFrameworks>
    <RepositoryType>git</RepositoryType>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Copyright>Copyright 2024-2026 Daniel T. Houck</Copyright>
    <Description>An implementation of the NetMq REQ-REP (Request/Reply) demonstrating multiple language IPC calls.</Description>
    <ApplicationIcon>Resources\IpcNetMq.ico</ApplicationIcon>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>IPC (REQuest/REPly) Using NetMq (ZeroMQ for .NET)</Title>
    <!-- <PackageIcon>Resources\IpcNetMq.png</PackageIcon> -->
    <!-- <PackageReadmeFile>README.md</PackageReadmeFile> -->
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageTags>NetMQ;ZeroMQ;IPC;InterProcessCommunication;</PackageTags>
    <PackageReleaseNotes>Updates to the client robustnes. Removed unneeded GDI reference. Timings are at 500 microSeconds RTT</PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression> <!-- or whatever you use -->
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <AssemblyVersion>26.1.8.0</AssemblyVersion>
    <FileVersion>26.1.8.0</FileVersion>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <CodeAnalysisRuleSet>ManagedMinimumRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="%28old%29\**" />
    <Compile Remove="Examples\**" />
    <Compile Remove="IpcNetMq.Tests\**" />
    <EmbeddedResource Remove="%28old%29\**" />
    <EmbeddedResource Remove="Examples\**" />
    <EmbeddedResource Remove="IpcNetMq.Tests\**" />
    <None Remove="%28old%29\**" />
    <None Remove="Examples\**" />
    <None Remove="IpcNetMq.Tests\**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="IpcClientInternal.cs" />
    <Compile Remove="IpcNetMq.cs" />
    <Compile Remove="IpcServerInfoElement.cs" />
    <Compile Remove="ReadStep.cs" />
    <Compile Remove="IpcPacket.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="LICENSE.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NetMQ" Version="4.0.2.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Documentation\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Update="Resources\IpcNetMq.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Resources\IpcNetMq.png">
      <Pack>False</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <!-- <Exec Command="PowerShell -NoProfile -ExecutionPolicy Bypass -Command &quot;&amp; { $targetFolder = [System.IO.Path]::Combine([Environment]::GetFolderPath([Environment+SpecialFolder]::MyDocuments), 'IpcTests'); Write-Host 'Target Folder:' $targetFolder; if (Test-Path -Path $targetFolder) { Write-Host 'Target folder already exists.' } else { Write-Host 'Target folder does not exist. Creating...'; New-Item -ItemType Directory -Force -Path $targetFolder; Write-Host 'Target folder created.' }; foreach ($file in Get-ChildItem \&quot;$(TargetDir)*\&quot; -File) { Copy-Item -Path $file.FullName -Destination $targetFolder; Write-Host 'Copied ' $file.Name ' to ' $targetFolder } }&quot;&#xD;&#xA;&#xD;&#xA;" /> -->
  </Target>
</Project>